# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.1

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/cvonelm/dev/pmu-events

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/cvonelm/dev/pmu-events/pmu-events

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/cvonelm/dev/pmu-events/pmu-events/CMakeFiles /home/cvonelm/dev/pmu-events/pmu-events//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/cvonelm/dev/pmu-events/pmu-events/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named pmu-events

# Build rule for target.
pmu-events: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 pmu-events
.PHONY : pmu-events

# fast build rule for target.
pmu-events/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pmu-events.dir/build.make CMakeFiles/pmu-events.dir/build
.PHONY : pmu-events/fast

#=============================================================================
# Target rules for targets named pmu-test

# Build rule for target.
pmu-test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 pmu-test
.PHONY : pmu-test

# fast build rule for target.
pmu-test/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pmu-test.dir/build.make CMakeFiles/pmu-test.dir/build
.PHONY : pmu-test/fast

examples/main.o: examples/main.c.o
.PHONY : examples/main.o

# target to build an object file
examples/main.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pmu-test.dir/build.make CMakeFiles/pmu-test.dir/examples/main.c.o
.PHONY : examples/main.c.o

examples/main.i: examples/main.c.i
.PHONY : examples/main.i

# target to preprocess a source file
examples/main.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pmu-test.dir/build.make CMakeFiles/pmu-test.dir/examples/main.c.i
.PHONY : examples/main.c.i

examples/main.s: examples/main.c.s
.PHONY : examples/main.s

# target to generate assembly for a file
examples/main.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pmu-test.dir/build.make CMakeFiles/pmu-test.dir/examples/main.c.s
.PHONY : examples/main.c.s

pmu-events.o: pmu-events.c.o
.PHONY : pmu-events.o

# target to build an object file
pmu-events.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pmu-events.dir/build.make CMakeFiles/pmu-events.dir/pmu-events.c.o
.PHONY : pmu-events.c.o

pmu-events.i: pmu-events.c.i
.PHONY : pmu-events.i

# target to preprocess a source file
pmu-events.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pmu-events.dir/build.make CMakeFiles/pmu-events.dir/pmu-events.c.i
.PHONY : pmu-events.c.i

pmu-events.s: pmu-events.c.s
.PHONY : pmu-events.s

# target to generate assembly for a file
pmu-events.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pmu-events.dir/build.make CMakeFiles/pmu-events.dir/pmu-events.c.s
.PHONY : pmu-events.c.s

src/kernel-defs.o: src/kernel-defs.c.o
.PHONY : src/kernel-defs.o

# target to build an object file
src/kernel-defs.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pmu-events.dir/build.make CMakeFiles/pmu-events.dir/src/kernel-defs.c.o
.PHONY : src/kernel-defs.c.o

src/kernel-defs.i: src/kernel-defs.c.i
.PHONY : src/kernel-defs.i

# target to preprocess a source file
src/kernel-defs.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pmu-events.dir/build.make CMakeFiles/pmu-events.dir/src/kernel-defs.c.i
.PHONY : src/kernel-defs.c.i

src/kernel-defs.s: src/kernel-defs.c.s
.PHONY : src/kernel-defs.s

# target to generate assembly for a file
src/kernel-defs.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pmu-events.dir/build.make CMakeFiles/pmu-events.dir/src/kernel-defs.c.s
.PHONY : src/kernel-defs.c.s

src/x86/util.o: src/x86/util.c.o
.PHONY : src/x86/util.o

# target to build an object file
src/x86/util.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pmu-events.dir/build.make CMakeFiles/pmu-events.dir/src/x86/util.c.o
.PHONY : src/x86/util.c.o

src/x86/util.i: src/x86/util.c.i
.PHONY : src/x86/util.i

# target to preprocess a source file
src/x86/util.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pmu-events.dir/build.make CMakeFiles/pmu-events.dir/src/x86/util.c.i
.PHONY : src/x86/util.c.i

src/x86/util.s: src/x86/util.c.s
.PHONY : src/x86/util.s

# target to generate assembly for a file
src/x86/util.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pmu-events.dir/build.make CMakeFiles/pmu-events.dir/src/x86/util.c.s
.PHONY : src/x86/util.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... pmu-events"
	@echo "... pmu-test"
	@echo "... examples/main.o"
	@echo "... examples/main.i"
	@echo "... examples/main.s"
	@echo "... pmu-events.o"
	@echo "... pmu-events.i"
	@echo "... pmu-events.s"
	@echo "... src/kernel-defs.o"
	@echo "... src/kernel-defs.i"
	@echo "... src/kernel-defs.s"
	@echo "... src/x86/util.o"
	@echo "... src/x86/util.i"
	@echo "... src/x86/util.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

